### ISSUE TITLE
finding a time slot for nachrueckmails is not endrecursive

### ISSUE THREAD

**Issue by noerw** [fs-geofs/ErstiWeTool#16]
...and thus may bust the call stack, after too many failed attempts of finding a fitting slot
```
Okt 23 22:07:32 geofs erstiwetool[1073]: /srv/ErstiWeTool/node_modules/mysql/lib/protocol/Parser.js:80
Okt 23 22:07:32 geofs erstiwetool[1073]:         throw err; // Rethrow non-MySQL errors
Okt 23 22:07:32 geofs erstiwetool[1073]:         ^
Okt 23 22:07:32 geofs erstiwetool[1073]: RangeError: Maximum call stack size exceeded
Okt 23 22:07:32 geofs erstiwetool[1073]:     at String.replace (<anonymous>)
Okt 23 22:07:32 geofs erstiwetool[1073]:     at regexEscape (/srv/ErstiWeTool/node_modules/moment/moment.js:684:18)
Okt 23 22:07:32 geofs erstiwetool[1073]:     at unescapeFormat (/srv/ErstiWeTool/node_modules/moment/moment.js:678:16)
Okt 23 22:07:32 geofs erstiwetool[1073]:     at getParseRegexForToken (/srv/ErstiWeTool/node_modules/moment/moment.js:670:31)
Okt 23 22:07:32 geofs erstiwetool[1073]:     at configFromStringAndFormat (/srv/ErstiWeTool/node_modules/moment/moment.js:2411:41)
Okt 23 22:07:32 geofs erstiwetool[1073]:     at configFromISO (/srv/ErstiWeTool/node_modules/moment/moment.js:2243:13)
Okt 23 22:07:32 geofs erstiwetool[1073]:     at configFromString (/srv/ErstiWeTool/node_modules/moment/moment.js:2353:9)
Okt 23 22:07:32 geofs erstiwetool[1073]:     at configFromInput (/srv/ErstiWeTool/node_modules/moment/moment.js:2594:13)
Okt 23 22:07:32 geofs erstiwetool[1073]:     at prepareConfig (/srv/ErstiWeTool/node_modules/moment/moment.js:2577:13)
Okt 23 22:07:32 geofs erstiwetool[1073]:     at createFromConfig (/srv/ErstiWeTool/node_modules/moment/moment.js:2544:44)
```
edit: Thats at least what I assume is happening because momentjs has no reason to grow such a call stack for a basic constructor.

Related code: https://github.com/fs-geofs/ErstiWeTool/blob/30ca4a4/lib/mailer.js#L122-L138

**Comment by noerw** [comment]
related: there are no checks whether a fitting time slot can be found at all (depending on min,max, current time, and time-restriction).
If that is the case, a constant should be added to [min,max] to move out of the time-restriction
